-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.NAME
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS b
ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE TO_CHAR(b.DATETIME - a.DATETIME) > 0
ORDER BY to_number(TO_CHAR(b.DATETIME - a.DATETIME)) DESC
FETCH FIRST 2 ROWS ONLY