SELECT TO_CHAR(a.SALES_DATE, 'yyyy-mm-dd') AS SALES_DATE, 
       a.PRODUCT_ID,
       a.USER_ID,
       a.SALES_AMOUNT
FROM ONLINE_SALE a
WHERE TO_CHAR(a.SALES_DATE, 'yyyy-mm') = '2022-03'

UNION ALL

SELECT TO_CHAR(b.SALES_DATE, 'yyyy-mm-dd') AS SALES_DATE,
       b.PRODUCT_ID,
       NULL AS USER_ID,
       b.SALES_AMOUNT
FROM OFFLINE_SALE b
WHERE TO_CHAR(b.SALES_DATE, 'yyyy-mm') = '2022-03'

ORDER BY 1,2,3;
