SELECT 
    TO_CHAR(START_DATE, 'FMMM') AS MONTH, 
    CAR_ID, 
    COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

WHERE 
    TO_CHAR(START_DATE, 'FMMM') IN ('8', '9', '10')
    AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'FMMM') IN ('8', '9', '10')
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5       
    )
GROUP BY 
    TO_CHAR(START_DATE, 'FMMM'), 
    CAR_ID
ORDER BY 
    TO_NUMBER(MONTH),
    CAR_ID DESC;
