-- 코드를 입력하세요
SELECT 
    a.PRODUCT_ID, 
    a.PRODUCT_NAME,
    SUM(a.PRICE * b.AMOUNT) TOTAL_SALES

FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b ON a.PRODUCT_ID = b.PRODUCT_ID

WHERE TO_CHAR(b.PRODUCE_DATE, 'yyyy-mm') = '2022-05'
GROUP BY 
    a.PRODUCT_ID, 
    a.PRODUCT_NAME

ORDER BY 3 DESC, 1