-- 코드를 입력하세요
SELECT 
    a.MEMBER_NAME,
    b.REVIEW_TEXT,
    TO_CHAR(b.REVIEW_DATE, 'yyyy-mm-dd') REVIEW_DATE
FROM MEMBER_PROFILE a
JOIN REST_REVIEW b ON a.MEMBER_ID = b.MEMBER_ID

WHERE b.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
     ORDER BY COUNT(*) DESC
    FETCH FIRST 1 ROWS ONLY
)

ORDER BY 3, 2