SELECT 
    TO_CHAR(START_DATE, 'FMMM') AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'FMMM') IN ('8', '9', '10')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
    )
AND TO_CHAR(START_DATE, 'FMMM') IN ('8', '9', '10')
GROUP BY 
    TO_CHAR(START_DATE, 'FMMM'), 
    CAR_ID
HAVING COUNT(*) > 0
ORDER BY TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')), 2 DESC