-- 코드를 입력하세요
SELECT DISTINCT a.CAR_ID AS CAR_ID

FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID

WHERE a.CAR_TYPE LIKE '%세단%'
AND TO_CHAR(b.START_DATE, 'mm') = '10'

GROUP BY a.CAR_ID
ORDER BY a.CAR_ID DESC