-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.NAME
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE TO_CHAR(a.DATETIME, 'yyyy-mm-dd hh24:mi:ss') > TO_CHAR(b.DATETIME, 'yyyy-mm-dd hh24:mi:ss')
ORDER BY a.DATETIME