SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (category, PRICE) IN 
    (SELECT category, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY category)
AND category IN ('과자', '국', '김치', '식용유')

GROUP BY CATEGORY, PRODUCT_NAME
ORDER BY 2 DESC